package com.fdmgroup.bankApi.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;

import jakarta.persistence.*;
@JsonTypeInfo(
	    use = JsonTypeInfo.Id.NAME,
	    include = JsonTypeInfo.As.PROPERTY,
	    property = "type"   // tells JSON which subclass to instantiate
	)
	@JsonSubTypes({
	    @JsonSubTypes.Type(value = SavingsAccount.class, name = "savings"),
	    @JsonSubTypes.Type(value = CheckingAccount.class, name = "checking")
	})

// Abstract base entity representing accounts in the banking system.
// This class is mapped using JPA inheritance and is extended by Savings Account and Checking Account.
@Entity
@Table(name = "ACCOUNT")
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Account {
	
	// Primary key for the Account table
    // Auto-generated by the database using IDENTITY strategy
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ACCOUNT_ID")
	private long accountId;
	
	// Account balance, cannot be null
	@Column(name = "BALANCE", nullable = false)
	private double balance;
	
	// Many accounts belong to one customer
	@ManyToOne
	@JsonBackReference // Prevents serializing back to Customer, stops infinite recursion
	@JoinColumn(name = "FK_CUST_ID")
	private Customer customer;
	
	// Default no-args constructor required by JPA.
	public Account() {}
	
	// Constructor to create a new account with balance and associated customer
	public Account(double balance, Customer customer)
	{
		this.balance = balance;
		this.customer = customer;
	}

	// Get unique account ID
	public long getAccountId() {
		return accountId;
	}

	// Get account balance
	public double getBalance() {
		return balance;
	}

	// Update account balance
	public void setBalance(double balance) {
		this.balance = balance;
	}

	// Get the customer owning this account
	public Customer getCustomer() {
		return customer;
	}

	// Set the customer owning this account
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}
}
