package com.fdmgroup.bankApi.model;

import jakarta.persistence.*;

//Address entity represents an address of a customer in the banking system.
//This class is mapped to the ADDRESS table in the database using JPA .
@Entity
@Table(name = "ADDRESS")
public class Address {
	
	// Primary key for the Address table.
	// Automatically generated by the database using IDENTITY strategy.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ADDRESS_ID")
	private long addressId;
	
	// Customer's street number address (cannot be null & cannot be updated).
	@Column(name = "STREET_NUMBER", nullable = false, updatable = false)
	private String streetNumber;
	
	// Postal code of the customer's address (cannot be null).
	@Column(name = "POSTAL_CODE", nullable = false)
	private String postalCode;
	
	// City where the customer lives (cannot be null).
	@Column(name = "CITY", nullable = false)
	private String city;
	
	// Province where the customer lives (cannot be null).
	@Column(name = "PROVINCE", nullable = false)
	private String province;

	// Default no-args constructor required by JPA.
	public Address() {}
	
	// Parameterized constructor used to create a new Address instance
	public Address(String streetNumber, String postalCode, String city, String province) {
		this.streetNumber = streetNumber;
		this.postalCode = postalCode;
		this.city = city;
		this.province = province;
	}

	// Get unique customer address ID
	public long getAddressId() {
		return addressId;
	}

	// Get customer's street address
	public String getStreetNumber() {
		return streetNumber;
	}

	// Get customer's postal code
	public String getPostalCode() {
		return postalCode;
	}
	
	// Update customer's postal code
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	// Get customer's city
	public String getCity() {
		return city;
	}

	// Update customer's city
	public void setCity(String city) {
		this.city = city;
	}

	// Get customer's province
	public String getProvince() {
		return province;
	}

	// Update customer's province
	public void setProvince(String province) {
		this.province = province;
	}
}
