package com.fdmgroup.bankApi.model;

import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonUnwrapped;

import jakarta.persistence.*;
@JsonTypeInfo(
	    use = JsonTypeInfo.Id.NAME,
	    include = JsonTypeInfo.As.PROPERTY,
	    property = "type" // JSON property used to determine subclass
	)
	@JsonSubTypes({
	    @JsonSubTypes.Type(value = Person.class, name = "person"),
	    @JsonSubTypes.Type(value = Company.class, name = "company")
	})

// Abstract base entity representing a customer in the banking system.
// This class is mapped using JPA inheritance and is extended by Person and Company.
// Stores all Customer subclasses in one table and uses CUSTOMER_TYPE column to distinguish between Person and Company.
@Entity
@Table(name = "CUSTOMER")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "CUSTOMER_TYPE")
public abstract class Customer {
	// Primary key for the Customer table.
	// Automatically generated by the database using IDENTITY strategy starting from 1001.
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "customer_seq")
	@SequenceGenerator(
	        name = "customer_seq",
	        sequenceName = "customer_sequence",
	        initialValue = 1001,
	        allocationSize = 1
	)
	@Column(name = "CUSTOMER_ID")
	private long customerId;
	
	//Customer's full name (cannot be null).
	@Column(name = "CUSTOMER_NAME", nullable = false)
	private String name;
	
	// Cascade automatically applies database operations on Customer to its Address.
	// JsonUnwrapped keeps the API response flat by merging Address fields into Customer JSON.
    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "FK_ADDRESS_ID")
    @JsonUnwrapped
    private Address address;
    
    // One customer can have multiple accounts; mapped by the "customer" field in Account.
    // CascadeType.ALL ensures account operations (save, delete, etc.) follow the customer.
    @OneToMany(mappedBy = "customer", cascade = CascadeType.ALL, fetch = FetchType.EAGER, orphanRemoval = true)
    @JsonManagedReference  // Serializes accounts but stops recursion back to Customer
    private List<Account> accounts  = new ArrayList<>();
	
	// Default no-args constructor required by JPA.
	public Customer() {}

	// Parameterized constructor used to create a new Customer instance
	public Customer(String name, Address address) {
		this.name = name;
		this.address = address;
	}

	// Get unique customer ID
	public long getCustomerId() {
		return customerId;
	}

	// Get customer name
	public String getName() {
		return name;
	}

	// Update customer's name
	public void setName(String name) {
		this.name = name;
	}

	// Get customer's address
	public Address getAddress() {
		return address;
	}

	// Update customer's address
	public void setAddress(Address address) {
		this.address = address;
	}	
	
	// Adds an account to this customer and sets the customer reference inside the Account.
	// This keeps both sides of the bidirectional relationship in sync.
	public void addAccount(Account account) {
	    accounts.add(account);
	    account.setCustomer(this);
	}
	
	// Sets the list of accounts for this customer
	public void setAccounts(List<Account> accounts) {
	    this.accounts = accounts != null ? accounts : new ArrayList<>();
	    for (Account account : this.accounts) {
	        account.setCustomer(this);
	    }
	}
	
	// Returns the list of accounts associated with this customer
	public List<Account> getAccounts() {
	    return accounts;
	}
}
